config/routes.rb
Rails.application.routes.draw do
  get 'joins/create'

  get 'joins/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'sessions#new'
  get 'sessions/new' => 'sessions#new'
  post 'sessions' => 'sessions#create'
  delete 'sessions/:id' => 'sessions#destroy'

  resources :groups
  resources :users, only: [:create]
  resources :joins, only: [:create, :destroy]

  # root GET    /                          sessions#new
  # sessions_new GET    /sessions/new(.:format)    sessions#new
  #     sessions POST   /sessions(.:format)        sessions#create
  #              DELETE /sessions/:id(.:format)    sessions#destroy
  #       groups GET    /groups(.:format)          groups#index
  #              POST   /groups(.:format)          groups#create
  #    new_group GET    /groups/new(.:format)      groups#new
  #   edit_group GET    /groups/:id/edit(.:format) groups#edit
  #        group GET    /groups/:id(.:format)      groups#show
  #              PATCH  /groups/:id(.:format)      groups#update
  #              PUT    /groups/:id(.:format)      groups#update
  #              DELETE /groups/:id(.:format)      groups#destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/join.rb
class Join < ApplicationRecord
  belongs_to :user
  belongs_to :org
end

app/models/org.rb
class Org < ApplicationRecord
  belongs_to :user
  has_many :joins, dependent: :destroy
  has_many :users, through: :joins, source: :user

  validates :name, presence:true, length: {minimum: 6 }
  validates :desc, presence:true, length: {minimum: 11}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :joins, dependent: :destroy
  has_many :orgs, dependent: :destroy
  has_many :joined_orgs, through: :joins, source: :joins
  
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name, :last_name, presence: true
  validates :email, presence:true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
  validates :password, length: { minimum: 6, maximum: 12 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

  def current_user
    User.find_by( id: session[:id]) if session[:id]
  end
  helper_method :current_user

  private
    def require_login 
      redirect_to sessions_new_path unless session[:id]
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login
  def index
    @orgs = Org.all
  end
  
  def create
    @org = Org.create(org_params)
    @like = Join.create(org_id: @org.id , user_id: current_user.id)
    puts @like.errors.full_messages
    if @org.valid?
      redirect_to groups_path
    else  
      flash[:errors] = @org.errors.full_messages
      redirect_to groups_path
    end
  end

  def destroy
    if Org.find_by(id: params[:id])
      @org = Org.find_by(id: params[:id])
      if current_user == @org.user
        @org.destroy
        redirect_to groups_path
      else
        flash[:errors] = "You cannot destroy this person org"
        redirect_to groups_path
      end
    else
      flash[:errors] = "Unable to find Group"
      redirect_to groups_path
    end
  end

  def show
    @org = Org.find_by(id: params[:id])

  end

  private

  def org_params
    params.require(:org).permit(:user_id, :name, :desc)
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
    before_action :require_login
    def create
        if Org.find_by(id: params[:join][:org_id])
            @org = Org.find_by(id: params[:join][:org_id])

            if !(@org.users.include?(User.find(current_user)))
                Join.create(joins_params)
            end
        end
        redirect_to group_path(params[:join][:org_id])
    end
  
    def destroy
        @join = Join.find_by(joins_params)
        if @join
            if current_user.id == @join.user.id
                @join.destroy
                redirect_to group_path(params[:join][:org_id])
            else  
                flash[:errors] = "You cannot destroy this join!"
                redirect_to group_path(params[:join][:org_id])
            end
        end
    end
  
    private
    def joins_params
      params.require(:join).permit( :user_id, :org_id,)
    end
  
  end
  

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        @user = User.find_by(email: params[:user][:email])
    
        if @user
          if @user.authenticate(params[:user][:password])
            session[:id] = @user.id
            return redirect_to groups_path
            
          end
          flash[:errors] = ["Invalid Email/Password"]
          return redirect_to sessions_new_path
        end
        flash[:errors] = ["User Does not Exist"]
        return redirect_to sessions_new_path
      end
    
      def destroy
        session.delete :id
        redirect_to sessions_new_path
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)

    if @user.valid?
      flash[:success] = "User has been created. Please log in"
        redirect_to sessions_new_path
    else  
      flash[:errors] = @user.errors.full_messages
      redirect_to sessions_new_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h3>Here are the organications you may join:</h3>
                <% @orgs.each do |org| %>
                    <div class="card p-3">
                        <h2><a href="<%= group_path(org.id) %>"><%= org.name %></a></h2>
                        <p>Members: <%= org.users.count %></p>
                        <p><%= org.desc %></p>
                        <% if current_user == org.user %>
                            <a href="<%= group_path(org.id)%>" data-method="delete">Delete Org</a>
                        <% end %>
                    </div>
                <%end %>
        </div>
        <div class="col">
            <form class="form-group" action="/groups" method="post">
                <input  type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="org[user_id]" value="<%= current_user.id %>">
                <p>Org Name: <input class="form-control" type="text" name="org[name]"></p>
                <p>Description: <textarea class="form-control"  name="org[desc]"cols="30" rows="10"></textarea></p>
                <input class="form-control" type="submit" value="Create">
            </form>
        </div>
    </div>
</div>

app/views/groups/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <h3><%= @org.name %></h3>
            <p><%= @org.desc %></p>
            <% if @org.users.include?(current_user) %>
                <form class="form-group" action="<%= join_path(@org.id) %>" method="post">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="_method" value="delete">
                    <input type="hidden" name="join[user_id]" value="<%= current_user.id %>">
                    <input type="hidden" name="join[org_id]" value="<%= @org.id %>">
                    <input class="form-control" type="submit" value="Leave Group">
                </form>
            <% else %>
                <form class="form-gorup" action="/joins" method="post">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="join[org_id]" value="<%= @org.id %>">
                    <input type="hidden" name="join[user_id]" value="<%= current_user.id %>">
                    <input class="form-control" type="submit" value="Join Group">
                </form>
            <% end %>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h4> Created By: <%= @org.user.first_name %> <%= @org.user.last_name %></h4>
            <h4>Members: <%= @org.users.count%></h4>
            
            <hr>
            <% @org.users.each do |u| %>
                <ul>
                <li><%= u.first_name%> <%= u.last_name %></li>
                </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyExam</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="bg-dark">
    <div class="container">
      <div class="row text-light justify-content-between">
        <div class="col">
        <% if current_user %>
        <h1>Welcome <%= current_user.first_name %></h1>
        <form action="/sessions/<%=current_user.id%>" method="post">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="_method" value="delete">
          <input type="submit" value="Log Out">
        </form>
        <button ><a class="text-dark" href="<%= groups_path %>">Home</a></button>
        <% else %>
        <h1>Welcome</h1>
        <% end %>
        </div>
      </div>
    </div>
  </header>

    <% if flash[:success] %>
      <p><%= flash[:success] %></p>
    <% end %>

  	<% if flash[:errors] %>
      <div id="alert">
        <p><%= flash[:errors] %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>